
variables:
  MYSQL_DATABASE: 'pm'
  MYSQL_USER: 'havt'
  MYSQL_PASSWORD: '1234'
  MYSQL_ROOT_PASSWORD: '123456aa'
  SERVICE_TAGS: 'dev'
  SERVICE_NAME: 'mysql'

before_script:
  - echo "Before script"
  - cd backend

building:
  stage: build
  script:
    - echo "Building"

testing:
  stage: test
  image: hacoi1day/php_7.4_test
  services:
    - name: mysql:5.7.33
      alias: mysql
  script:
    - echo "Testing"
    - composer install
    - php artisan migrate --seed
    - php artisan passport:keys --force
    - php artisan passport:client --personal
    - php vendor/bin/phpunit
  
deploying:
  stage: deploy
  tags:
    - local
  environment:
    name: production
    url: http://pm.local
  only:
    - master
  script:
    - echo "Deploying"
    - chmod og= $ID_RSA
    - apk update && apk add openssh-client
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
    - echo "OK"