
variables:
  MYSQL_DATABASE: 'pm'
  MYSQL_USER: 'havt'
  MYSQL_PASSWORD: '1234'
  MYSQL_ROOT_PASSWORD: '123456aa'
  SERVICE_TAGS: 'dev'
  SERVICE_NAME: 'mysql'

testing:
  stage: test
  image: hacoi1day/php_7.4_test
  services:
    - name: mysql:5.7.33
      alias: mysql
  script:
    - echo "Testing"
    - pwd
    - cd backend
    - composer install
    - php artisan migrate --seed
    - php artisan passport:keys --force
    - php artisan passport:client --personal
    - php vendor/bin/phpunit

deploying:
  stage: deploy
  tags:
    - shell
  script:
    - echo "Deploying"
    - pwd
    - docker-compose up -d --build
    - make setup
  environment:
    name: production
    url: http://192.168.159.129
  only:
    - master
