image: hacoi1day/php_7.4_test

before_script:
  - echo "Before script"
  - cd backend

building:
  stage: build
  script:
    - echo "Building"
    - ls
    - composer install
    - php artisan migrate --seed
    - php artisan passport:keys --force
    - php artisan passport:client --personal

testing:
  stage: test
  script:
    - echo "Testing"
    # - php vendor/bin/phpunit --coverage-text --colors=never
  
deploying:
  stage: deploy
  script:
    - echo "Deploying"