before_script:
  - echo "Before script"
  - docker-compose up -d
  - pwd
  - ls
  # - cd backend

stages:
  - build
  - test

building:
  stage: build
  script:
    - composer install

unit_test:
  stage: test
  script:
    - pwd
    - ls
    - php ./vendor/bin/phpunit --coverage-text --colors=never
    # - cd backend
    # - composer install
    # - php artisan key:generate
    # - php artisan migrate
    # - php artisan passport:keys --force
    # - php artisan passport:client --personal
    # - vendor/bin/phpunit
  