image:

services:

variables:
  MYSQL_DATABASE: pm
  MYSQL_ROOT_PASSWORD: 123456aa
  DB_HOST: mysql
  DB_USERNAME: havt
  DB_PASSWORD: 1234

stages:
  - test

unit_test:
  stage: test
  script:
    - pwd
    - ls
    # - cd backend
    # - composer install
    # - php artisan key:generate
    # - php artisan migrate
    # - php artisan passport:keys --force
    # - php artisan passport:client --personal
    # - vendor/bin/phpunit
  