before_script:
  - echo "Before script"
  - cd backend

building:
  stage: build
  script:
    - echo "Building"
    - ls

testing:
  stage: test
  script:
    - echo "Testing"
  
deploying:
  stage: deploy
  script:
    - echo "Deploying"