version: '3'

networks:
  app_network:

services: 
  nginx:
    image: nginx:stable-alpine
    ports: 
      - 80:80
    volumes: 
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:5.7.33
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    tty: true
    ports: 
      - 3306:3306
    environment: 
      # MYSQL_DATABASE: pm
      # MYSQL_USER: havt
      # MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 123456aa
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks: 
      - app_network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - "8081:80"
    environment:
      # PMA_ARBITRARY: 1
      PMA_HOST: mysql
      # PMA_USER: root
      # PMA_PORT: 3306
      # PMA_PASSWORD: 123456aa
    networks: 
      - app_network
  
  backend:
    image: pm_backend
    volumes: 
      - ./backend:/var/www/html/backend
    ports: 
      - 9000:9000
    networks: 
      - app_network
    